export const DATA = {
  name: "Rey Joel L. Matugas",
  initials: "RJ",
  role: "Senior Full Stack Engineer",
  focus: "Backend Specialist",
  location: "Mandaue City, Cebu, Philippines",
  phone: "0961-932-4307",
  email: "reyjoelmatugas@gmail.com",
  github: "https://github.com/reyjoel",
  githubHandle: "reyjoel",
  linkedin: "https://www.linkedin.com/in/rey-joel-matugas",
  yearsExp: 9,
  summary: "Senior Full Stack Engineer with 9+ years of experience designing, developing, and scaling high-performance web applications and APIs. Expert in PHP (Laravel), Node.js, and modern JavaScript frameworks including React.js and Next.js. Strong experience in system design, RESTful API architecture, microservices, database optimization, caching strategies, and scalable backend infrastructure.",
  longSummary: "Proven ability to improve application performance, optimize complex SQL queries, and build reliable systems that support high-traffic platforms. Experienced working in Agile teams and collaborating with product, design, and engineering leadership to deliver production-ready solutions.",
  skills: {
    "Backend":      ["PHP", "Laravel", "Node.js", "Express.js", "NestJS", "CodeIgniter"],
    "Frontend":     ["React.js", "Next.js", "Vue.js", "AngularJS", "TailwindCSS", "jQuery", "HTML5", "CSS3", "JavaScript"],
    "API":          ["REST", "Webhooks", "OAuth", "JWT", "Swagger"],
    "Architecture": ["Microservices", "Scalable Systems", "Distributed Systems"],
    "Databases":    ["PostgreSQL", "MySQL", "Data Modeling", "Indexing", "Query Optimization", "Supabase"],
    "Performance":  ["Redis", "API tuning", "Database tuning", "Caching"],
    "DevOps":       ["AWS", "Docker", "Nginx", "CI/CD", "Git", "Linux", "GCP"],
    "Workflow":     ["Agile", "Scrum", "Postman", "Insomnia"],
    "AI":           ["Claude Code", "n8n", "OpenClaw", "Codex", "Gemini"],
  },
  experience: [
    {
      company: "Cody Web Development Inc.",
      role: "Backend Developer",
      period: "Jul 2023 — Present",
      location: "Cebu, PH",
      bullets: [
        "Develop scalable backend services using Laravel and Node.js for production web platforms.",
        "Design RESTful APIs and backend services supporting frontend applications and third-party integrations.",
        "Improve application performance through database indexing, query optimization, and backend refactoring.",
        "Design database schemas and implement scalable data models using PostgreSQL and MySQL.",
        "Collaborate with frontend developers and product teams in Agile development cycles.",
      ],
      stack: ["Laravel", "Node.js", "PostgreSQL", "MySQL"],
    },
    {
      company: "Expertel Solutions",
      role: "Web Developer / Senior Developer",
      period: "Jan 2021 — Jun 2023",
      location: "Cebu, PH",
      bullets: [
        "Developed full stack web applications using Laravel, JavaScript frameworks, and WordPress.",
        "Designed backend APIs supporting CRM, lead generation, and marketing automation systems.",
        "Integrated third-party APIs including payment systems, marketing platforms, and external services.",
        "Improved system performance by optimizing SQL queries and backend processes.",
        "Delivered multiple production platforms used by international clients.",
      ],
      stack: ["Laravel", "WordPress", "JavaScript", "REST APIs"],
    },
    {
      company: "PhotoUp Philippines",
      role: "Backend Developer",
      period: "Apr 2019 — Jan 2021",
      location: "Cebu, PH",
      bullets: [
        "Maintained and enhanced backend systems used by internal business operations.",
        "Implemented new backend features and optimized existing services for reliability and performance.",
        "Debugged production issues and ensured stable backend deployments.",
      ],
      stack: ["PHP", "MySQL", "Backend Services"],
    },
    {
      company: "TimeRiverDesign Inc.",
      role: "Web Developer",
      period: "Jun 2017 — Aug 2018",
      location: "Cebu, PH",
      bullets: [
        "Built dynamic websites and web applications using PHP and modern frontend technologies.",
        "Implemented backend functionality, CMS integrations, and performance improvements.",
      ],
      stack: ["PHP", "CMS", "Frontend"],
    },
    {
      company: "KONSUM Technologies",
      role: "Software Engineer",
      period: "Sep 2016 — May 2017",
      location: "Cebu, PH",
      bullets: [
        "Developed internal web applications and backend tools.",
        "Investigated and resolved system issues in production environments.",
      ],
      stack: ["Web Apps", "Backend Tools"],
    },
  ],
  projects_length: "10+",
  projects: [
    { name: "HireLens AI",             url: "https://sigma-resume-analyzer.vercel.app/",  tag: "Resume Analyzer" },
    { name: "PhotoUp",                 url: "https://www.photoup.net",                    tag: "Real Estate Tech" },
    { name: "Telesource",              url: "https://telesource.com.ph/",                 tag: "VA Recruitment" },
    { name: "Rubyrate",                url: "https://rubyrate.com/",                      tag: "Marketing Site" },
    { name: "Hireplus UK",             url: "https://www.hireplus.co.uk",                 tag: "Recruitment" },
    { name: "Agency Staff Solutions",  url: "https://dashboard.agencystaffsolutions.com", tag: "Dashboard" },
    { name: "Expertel Solutions",      url: "https://expertelsolutions.com",              tag: "Agency" },
    { name: "Leadstown",               url: "https://leadstown.com",                      tag: "Lead Generation" },
    { name: "Involved Leads",          url: "https://involvedleads.com",                  tag: "Marketing Site" },
    { name: "Involved Leads — App",    url: "https://app.involvedleads.com",              tag: "Web App" },
    { name: "Call Media Group",        url: "https://callmediagroup.com",                 tag: "Media" },
  ],
  certifications: [
    {
      name: "The Artificial Intelligence for Communities Workshop",
      issuer: "VJAL AI",
      url: "https://cert.vjal.ai/certificate/?uid=6485216460229317820",
    },
  ],
  education: [
    { school: "Cebu Technological University — Main Campus", degree: "Bachelor's Degree" },
  ],
  languages: ["English", "Filipino (Tagalog)", "Cebuano (Visayan)"],
}
